
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zovddtldwqxlgjpprddb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvdmRkdGxkd3F4bGdqcHByZGRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1NzI3NDQsImV4cCI6MjA1OTE0ODc0NH0.-MSTJqiuR3XdHIVbLKTMsym1_yvZuZEvQSIl_ltwTnQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
      flowType: 'pkce',
      storage: typeof window !== 'undefined' ? localStorage : undefined
    }
  }
);

// Note: Storage buckets 'profiles' and 'covers' are already created

// Export a helper to run raw SQL queries for tables not in TypeScript definitions
export const runQuery = async (query: string, params?: any[]) => {
  // Since we can't use the run_query RPC due to TypeScript limitations,
  // we'll use a workaround for now - using any to bypass TypeScript checking
  // for this specific call
  const client = supabase as any;
  const { data, error } = await client.rpc('run_query', { query, params });
  if (error) throw error;
  return { data, error: null };
};
